title: Best page ever 
author: Martin Becker
email: mbecker@de.ibm.com
description: > # this means to ignore newlines until "baseurl:"
  Wellcome on my page and have fun

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
